default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["DB_POOL"] || 5  %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  # host: <%= ENV["DB_HOST"] %>
  # url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
  # reconnect: true

development:
  <<: *default
  database: demo_ruby_jets_development

test:
  <<: *default
  database: demo_ruby_jets_test

production:
  <<: *default
  database: demo_ruby_jets_production
  url: <%= ENV['DATABASE_URL'] %>
